USE gr691_msi
GO

CREATE TABLE Student
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_Group_ID INT,
	Last_Name NVARCHAR(100),
	First_Name NVARCHAR(100),
	Middle_Name NVARCHAR(100),
	Date_Of_Birth DATE,
	Login NVARCHAR(20),
	Password NVARCHAR(20)
)

CREATE TABLE Teacher
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Last_Name NVARCHAR(100),
	First_Name NVARCHAR(100),
	Middle_Name NVARCHAR(100),
	Date_Of_Birth DATE,
	Login NVARCHAR(20),
	Password NVARCHAR(20)
)

CREATE TABLE Specialty
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100),
	Code NVARCHAR(15)
)

CREATE TABLE [Group]
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_Faculty_ID INT,
	FK_Student_ID INT,
	FK_Course_ID INT,
	FK_Specialty_ID INT,
	FK_Teacher_ID INT,
	Name NVARCHAR(20)
)

CREATE TABLE Faculty
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100)
)

CREATE TABLE Course
(
	ID INT PRIMARY KEY
)

CREATE TABLE Subject
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100),
	FK_Teacher_ID INT
)

CREATE TABLE Mark
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_Subject_ID INT,
	FK_Student_ID INT,
	Date DATE,
	Mark NVARCHAR(1)
)

CREATE TABLE Homework
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_Subject_ID INT,
	FK_Group_ID INT,
	Date_Of_Issue DATE,
	Description NVARCHAR(200),
	Status NVARCHAR(100)
)

CREATE TABLE Subject_Group
(
	PK_FK_Subject_ID INT,
	PK_FK_Group_ID INT
	PRIMARY KEY (PK_FK_Subject_ID, PK_FK_Group_ID)
)

ALTER TABLE Student ADD FOREIGN KEY (FK_Group_ID) REFERENCES [Group] (ID)

ALTER TABLE Subject ADD FOREIGN KEY (FK_Teacher_ID) REFERENCES Teacher (ID)

ALTER TABLE Subject_Group ADD FOREIGN KEY (PK_FK_Subject_ID) REFERENCES Subject (ID)
ALTER TABLE Subject_Group ADD FOREIGN KEY (PK_FK_Group_ID) REFERENCES [Group] (ID)

ALTER TABLE Mark ADD FOREIGN KEY (FK_Subject_ID) REFERENCES Subject (ID)
ALTER TABLE Mark ADD FOREIGN KEY (FK_Student_ID) REFERENCES Student (ID)

ALTER TABLE Homework ADD FOREIGN KEY (FK_Subject_ID) REFERENCES Subject (ID)
ALTER TABLE Homework ADD FOREIGN KEY (FK_Group_ID) REFERENCES [Group] (ID)

ALTER TABLE [Group] ADD FOREIGN KEY (FK_Faculty_ID) REFERENCES Faculty (ID)
ALTER TABLE [Group] ADD FOREIGN KEY (FK_Student_ID) REFERENCES Student (ID)
ALTER TABLE [Group] ADD FOREIGN KEY (FK_Course_ID) REFERENCES Course (ID)
ALTER TABLE [Group] ADD FOREIGN KEY (FK_Specialty_ID) REFERENCES Specialty (ID)
ALTER TABLE [Group] ADD FOREIGN KEY (FK_Teacher_ID) REFERENCES Teacher (ID)

